// DEPRECATED / UNUSED — no live traffic routes here as of 2026-09-17.
// Written as a Vercel serverless function (req.query / res.json) — this
// repo is a static GitHub Pages site with no build step or serverless
// runtime, so this file was never actually executed there. The real DeoVR
// JSON is generated by the separate Cloudflare Worker at
// vrkings-proxy.vrkings-r.workers.dev/deovr (param is `url=`, not `v=` —
// another mismatch confirming this was never the live source). Left in
// place (moved to /deprecated/) rather than deleted — see the player audit
// for the full explanation.
export default function handler(req, res) {
  const { v, type, title } = req.query;

  if (!v) {
    res.status(400).json({ error: 'Missing video URL parameter ?v=' });
    return;
  }

  const is180 = type === 'sbs' || type === '180';

  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Access-Control-Allow-Origin', '*');

  res.json({
    title: decodeURIComponent(title || 'VR KINGS'),
    is3d: true,
    screenType: is180 ? 'dome' : 'sphere',
    stereoMode: is180 ? 'sbs' : 'mono',
    skipIntro: 0,
    videoLength: 0,
    encodings: [{
      name: 'h264',
      videoSources: [{ resolution: 3840, url: decodeURIComponent(v) }]
    }]
  });
}
